hosts:
  production:
    hostname: dedi2835.your-server.de
    remote_user: transm
    port: 222
    labels:
      stage: production
    deploy_path: '~/public_html/resources/wp-content/themes'
    branch: main
